=== timmyCoder/vscode-user-status/src/schemas/status.json
{
  "$id": "https://example.com/address.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "statusDetails": {
      "type": "object",
      "properties": {
        "slack": {
          "type": "object",
          "properties": {
            "emoji_name": {
              "type": "string"
            }
          },
          "required": ["emoji_name"]
        },
        "github": {
          "type": "object",
          "properties": {
            "emoji_name": {
              "type": "string"
            }
          },
          "required": ["emoji_name"]
        },
        "text": {"type": "string"}
      }
    }
  },
  "type": "object",
  "properties": {
    "ğŸ¯": {
      "$ref": "#/definitions/statusDetails"
    },
    "â˜•": {
      "$ref": "#/definitions/statusDetails"
    },
    "ğŸ—“": {
      "$ref": "#/definitions/statusDetails"
    },
    "ğŸšŒ": {
      "$ref": "#/definitions/statusDetails"
    },
    "ğŸŒ´": {
      "$ref": "#/definitions/statusDetails"
    },
    "ğŸ¡": {
      "$ref": "#/definitions/statusDetails"
    },
    "ğŸ¤’": {
      "$ref": "#/definitions/statusDetails"
    }
  },
  "required": ["ğŸ¯", "â˜•", "ğŸ—“", "ğŸšŒ", "ğŸŒ´", "ğŸ¡", "ğŸ¤’"],
  "additionalProperties": false
}

=== timmyCoder/vscode-user-status/src/i18n/en/status.json
{
  "ğŸ¯": {
    "slack": {
      "emoji_name": "dart"
    },
    "github": {
      "emoji_name": "dart"
    },
    "text": "Focusing"
  },
  "â˜•": {
    "slack": {
      "emoji_name": "coffee"
    },
    "github": {
      "emoji_name": "coffee"
    },
    "text": "Taking a break"
  },
  "ğŸ—“": {
    "slack": {
      "emoji_name": "spiral_calendar_pad"
    },
    "github": {
      "emoji_name": "spiral_calendar"
    },
    "text": "In a meeting"
  },
  "ğŸšŒ": {
    "slack": {
      "emoji_name": "bus"
    },
    "github": {
      "emoji_name": "bus"
    },
    "text": "On my way to work"
  },
  "ğŸŒ´": {
    "slack": {
      "emoji_name": "palm_tree"
    },
    "github": {
      "emoji_name": "palm_tree"
    },
    "text": "On Vacation"
  },
  "ğŸ¡": {
    "slack": {
      "emoji_name": "house_with_garden"
    },
    "github": {
      "emoji_name": "house_with_garden"
    },
    "text": "Working from home"
  },
  "ğŸ¤’": {
    "slack": {
      "emoji_name": "face_with_thermometer"
    },
    "github": {
      "emoji_name": "face_with_thermometer"
    },
    "text": "Out sick"
  }
}

=== timmyCoder/vscode-user-status/src/i18n/ja/status.json
{
  "ğŸ¯": {
    "slack": {
      "emoji_name": "dart"
    },
    "github": {
      "emoji_name": "dart"
    },
    "text": "é›†ä¸­"
  },
  "â˜•": {
    "slack": {
      "emoji_name": "coffee"
    },
    "github": {
      "emoji_name": "coffee"
    },
    "text": "ä¼‘æ†©ä¸­"
  },
  "ğŸ—“": {
    "slack": {
      "emoji_name": "spiral_calendar_pad"
    },
    "github": {
      "emoji_name": "spiral_calendar"
    },
    "text": "ä¼šè­°ä¸­"
  },
  "ğŸšŒ": {
    "slack": {
      "emoji_name": "bus"
    },
    "github": {
      "emoji_name": "bus"
    },
    "text": "é€šå‹¤é€”ä¸­"
  },
  "ğŸŒ´": {
    "slack": {
      "emoji_name": "palm_tree"
    },
    "github": {
      "emoji_name": "palm_tree"
    },
    "text": "ä¼‘æš‡ä¸­"
  },
  "ğŸ¡": {
    "slack": {
      "emoji_name": "house_with_garden"
    },
    "github": {
      "emoji_name": "house_with_garden"
    },
    "text": "ãƒªãƒ¢ãƒ¼ãƒˆã§ä½œæ¥­ä¸­"
  },
  "ğŸ¤’": {
    "slack": {
      "emoji_name": "face_with_thermometer"
    },
    "github": {
      "emoji_name": "face_with_thermometer"
    },
    "text": "ç—…æ¬ "
  }
}
